# Generated by Django 4.2.13 on 2024-05-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='charginglogic',
            name='rule_application_period',
        ),
        migrations.AddField(
            model_name='charginglogic',
            name='days',
            field=models.ManyToManyField(to='core.day'),
        ),
        migrations.AddField(
            model_name='charginglogic',
            name='months',
            field=models.ManyToManyField(to='core.month'),
        ),
        migrations.AddField(
            model_name='charginglogic',
            name='years',
            field=models.ManyToManyField(to='core.year'),
        ),
    ]
