# Generated by Django 4.2.13 on 2024-05-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='charginglogic',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
