# Generated by Django 4.2.13 on 2024-05-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='charginglogic',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
