# Generated by Django 4.2.13 on 2024-06-01 19:16

from django.db import migrations, models
from django.utils import timezone 


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_day_month_year_and_more'),
        ('core', '0004_charginglogic_is_enabled'),
    ]

    operations = [
        # Add the rule_application_period field back to the ChargingLogic model
        migrations.AddField(
            model_name='charginglogic',
            name='rule_application_period',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        # Add the last_check_in field to the User model
        migrations.AddField(
            model_name='user',
            name='last_check_in',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
