# Generated by Django 4.2.13 on 2024-05-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_charginglogic_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charginglogic',
            name='enabled',
        ),
    ]
