# Generated by Django 4.2.13 on 2024-06-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20240602_0316'),
    ]

    operations = [
    ]
