# Generated by Django 4.2.13 on 2024-06-12 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_conflicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='charginglogic',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        # Comment out the line that adds the 'rule_application_period' column
        # migrations.AddField(
        #     model_name='charginglogic',
        #     name='rule_application_period',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        migrations.AddField(
            model_name='transactionhistory',
            name='amount_rate',
            field=models.CharField(choices=[('second', 'Per Second'), ('minute', 'Per Minute'), ('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month')], default='hour', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='last_check_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
