name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: 'gcloud'

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/django-app:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/django-app:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy django-app \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/django-app:${{ github.sha }} \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }},STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }},DEBUG=${{ secrets.DEBUG }}
